### ISSUE TITLE
Where is the lib file?

### ISSUE THREAD

**Issue by wenbang24** [daprice/keyswitches.pretty#10]
I want to add it to my project but i can't find a .lib file for the schematic

**Comment by daprice** [comment]
This library only contains footprints for the board editor, not schematic symbols which is what .lib is for. For a keyboard schematic, the switches could just be SW_Push from the standard library, and then you would assign the footprint you want from the .pretty library, see [Masterzen’s tutorial](https://www.masterzen.fr/2020/05/25/designing-a-keyboard-part2/#the-matrix) for an example
