### ISSUE TITLE
Eagle CAD support?

### ISSUE THREAD

**Issue by amin-mm-dev** [daprice/keyswitches.pretty#11]
Hi there!
Would it be possible to add support for people working with Eagle CAD software? I find it hard to design on KiCAD and constantly export models to Fusion 360 (it's my preferred 3d modeling CAD). I'd really appreciate it if there's a chance anyone can help with this!

P.S: I did some research only but couldn't find a way to convert KiCAD libraries to Eagle :/

Thanks all!

**Comment by daprice** [comment]
It’s outside the scope of this repo, but if someone wanted to make their own fork to port it to other software, I’d consider adding a link to it in the readme.
